
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 76
#define YY_END_OF_BUFFER 77
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[228] =
    {   0,
        0,    0,    0,    0,    0,    0,   77,   75,   73,   74,
       63,   75,   46,   47,   39,   36,   51,   37,   50,   60,
       60,   54,   48,   35,   53,   34,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   55,   56,   75,   69,   66,
       66,   66,   64,   68,   72,   71,   70,    0,    0,   49,
       61,    0,    0,    0,   60,   52,   32,   33,   31,   59,
       59,   59,    0,   59,   59,   59,   59,   59,   59,   24,
       59,   59,   59,   59,   59,   59,   18,   59,   59,   59,
       59,    6,   38,   59,   59,   59,   59,   59,   59,   27,

       59,   59,   59,   59,   59,   59,   67,   66,   65,   66,
       62,    0,    0,   61,    0,    0,   61,   61,    0,   60,
       42,   59,   59,   59,   59,   59,   59,   59,   59,   40,
       59,   59,   17,   59,   25,   59,   59,   59,   59,   41,
       43,   59,   59,   59,   59,   59,   59,   59,   59,    7,
       59,   59,    0,   61,   61,   61,   61,   60,   59,   59,
       59,   21,   14,   59,   59,   59,   20,   59,   59,   59,
       44,   59,   59,   59,   59,   59,   28,   12,   59,   45,
       19,   57,    3,   59,   59,   61,    5,   16,   59,    2,
       59,   59,   58,   59,   59,   59,   59,   59,   59,   59,

       59,   23,   29,   59,    4,   26,   59,   59,   59,   30,
       59,   59,   59,   15,   13,    8,   59,   11,   59,   59,
        1,    9,   59,   59,   22,   10,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    6,    6,    6,    6,    8,    9,
       10,   11,   12,   13,   14,   15,    6,   16,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,    6,    6,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   32,   33,   34,   35,   36,   37,
       32,   38,   39,   40,   41,   42,   43,   44,   45,   32,
       46,   47,   48,    6,   49,    6,   50,   51,   52,   53,

       54,   55,   56,   57,   58,   32,   32,   59,   60,   61,
       62,   63,   32,   64,   65,   66,   67,   68,   69,   70,
       71,   32,   72,    6,   73,    6,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[74] =
    {   0,
        1,    1,    1,    1,    2,    2,    2,    3,    2,    2,
        2,    2,    2,    2,    4,    5,    6,    2,    2,    2,
        2,    2,    7,    8,    7,    7,    7,    8,    9,    9,
        9,    9,    9,    9,   10,    9,    9,   10,    9,   10,
        9,   10,    9,    9,    9,    2,    2,    2,   11,    7,
        8,    7,    7,    7,    8,    9,    9,    9,    9,    9,
       10,    9,    9,   10,    9,   10,    9,   10,    9,    9,
        9,    2,    2
    } ;

static const flex_int16_t yy_base[239] =
    {   0,
        0,    0,   71,   73,   76,   78,  647,  648,  648,  648,
      648,  580,  648,  648,  648,  648,  648,  648,   67,   70,
       71,  603,  648,   68,  648,  601,   58,   67,   81,   74,
       93,  112,  572,   85,  109,  106,  110,  114,  128,  129,
      142,  131,  175,  150,  152,  648,  648,    0,  648,  648,
      648,  617,  648,   88,  648,  648,  648,  611,  553,  648,
      168,   83,  190,  545,  202,  648,  648,  648,  648,  510,
      161,  174,  501,  159,  185,  187,  204,  200,   59,  199,
      194,  202,  211,  220,  196,  227,  500,  222,  229,  240,
      225,  499,  490,  243,  236,  252,  245,  248,  254,  489,

      246,  262,  258,  274,  279,  482,  648,  648,  648,  522,
      648,  511,  298,  300,  317,  302,  648,  304,    0,  484,
      447,  289,  445,  293,  297,  299,  298,  296,  303,  443,
      306,  316,  428,  310,  314,  319,  324,  331,  335,  400,
      393,  333,  347,  348,  355,  346,  353,  362,  363,  390,
      359,  360,  377,  648,  403,  405,    0,  416,  361,  380,
      396,  375,  349,  385,  394,  388,  329,  403,  410,  395,
      320,  407,  398,  417,  413,  420,  255,  237,  430,  233,
      231,  214,  191,  419,  421,  455,  181,  154,  451,  140,
      449,  444,  137,  440,  456,  458,  453,  439,  460,  467,

      466,  132,  126,  462,  116,  108,  492,  484,  483,   98,
      493,  485,  494,   96,   92,   66,  495,   64,  488,  491,
       60,   57,  508,  509,   53,   46,  648,  563,  574,  584,
      591,  596,  606,  615,  622,  626,  633,  638
    } ;

static const flex_int16_t yy_def[239] =
    {   0,
      227,    1,  228,  228,  229,  229,  227,  227,  227,  227,
      227,  230,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  227,  227,  232,  227,  227,
      227,  227,  227,  233,  227,  227,  227,  227,  234,  227,
      227,  227,  227,  235,  227,  227,  227,  227,  227,  231,
      231,  231,  236,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,

      231,  231,  231,  231,  231,  231,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  237,  238,
      231,  231,  236,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  227,  227,  227,  227,  237,  238,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  227,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,

      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  231,    0,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227
    } ;

static const flex_int16_t yy_nxt[722] =
    {   0,
        8,    9,   10,    8,    9,    8,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   33,   36,   37,   38,   39,   40,   41,   42,   43,
       33,   44,   45,   33,   33,   46,    8,   47,   48,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   33,   44,   45,   33,
       33,   49,    8,   51,   52,   51,   52,   53,   56,   53,
       56,   60,   61,   61,   62,   62,   65,   65,   67,   68,
      109,  110,   71,   74,   73,   72,   63,   63,   61,   61,

      130,   73,   75,   76,   79,   73,   73,   73,   73,   80,
       77,   86,   73,   64,   73,   73,   78,   54,   71,   54,
       74,   72,   73,   63,   63,   81,  130,   82,   75,   73,
       76,   79,   89,   73,   83,   80,   87,   77,   86,   64,
       73,   73,   78,   88,   73,   90,   73,   84,   57,   91,
       57,   81,   85,   82,   73,   92,   73,   73,   73,   89,
       73,   83,   73,   87,   73,   93,   95,   94,   96,   88,
       97,   90,  103,   84,   73,   91,   73,   73,   85,   73,
       73,  104,   92,  113,  114,   73,  121,  124,   73,  105,
       73,   93,   95,   94,  115,   96,   97,   98,   73,  103,

       73,  116,   73,  116,   99,  117,  118,   73,  104,   73,
      100,  122,  101,  121,  124,  105,   62,   65,   65,  102,
      125,  115,   73,   73,   98,  126,  127,  133,   63,   73,
      136,   99,  132,   73,  128,   73,  100,  122,  101,   73,
      129,  131,   73,  134,   73,  102,  125,   73,   73,  137,
       73,  126,   73,  127,  133,   63,  136,  135,  132,   73,
      128,  138,   73,  139,  141,  140,  129,  131,   73,  134,
       73,  143,  142,   73,  144,   73,  137,   73,  146,   73,
      147,   73,  145,  135,   73,   73,  148,  138,   73,  139,
      141,   73,  140,   73,   73,  150,   73,  143,  149,  142,

       73,  144,   73,   73,  151,  146,   73,  147,  145,  152,
       73,  159,  148,  113,  114,  113,  114,  117,  118,  156,
      156,  150,   73,  160,  149,  162,  115,   73,  153,  161,
      153,  151,  154,  155,  164,  163,  152,   73,  159,  165,
      166,   73,  167,  170,   73,   73,   73,   73,  168,  171,
      160,   73,  162,  115,   73,  161,  169,  172,   73,  174,
      164,  163,   73,  173,   73,  165,  166,   73,   73,  167,
      170,  175,   73,  177,  168,  176,  171,   73,  180,   73,
      178,   73,  169,   73,  172,  179,  174,  181,  182,  183,
      173,  184,  154,  155,   73,   73,   73,   73,  175,  185,

      177,   73,  176,   73,  180,  187,  178,   73,   73,   73,
       73,   73,  179,  181,  188,  182,  183,  184,  186,  186,
      156,  156,  189,   73,  190,  185,  191,  192,   73,  193,
      119,  187,  194,   73,  195,  196,   73,  197,   73,  199,
      188,   73,   73,   73,   73,  202,   73,  203,   73,  189,
      190,   73,  191,  192,  198,   73,  193,  200,   73,  194,
      195,   73,  196,  197,  201,   73,  199,   73,   73,   73,
      186,  186,  202,  204,  203,  205,   73,  207,   73,  206,
      198,  211,  210,  200,  209,  212,  208,   73,   73,  213,
      201,   73,   73,   73,  214,   73,  215,   73,  119,   73,

      204,   73,  205,  207,   73,  206,   73,  211,   73,  210,
       73,  209,  212,  208,   73,   73,  213,  216,  111,  217,
      218,  214,  215,  219,  109,  220,  223,  221,  224,  222,
       73,   73,   73,   73,  225,  226,   73,   73,   73,   73,
       73,   73,   73,   73,  216,  217,  218,   73,   73,   73,
      219,  220,  223,  221,  224,  222,   73,   73,   73,  119,
      111,  225,  226,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   70,   70,   70,   70,   70,

       70,   70,  106,  106,  106,  106,  108,  108,  108,  108,
      108,  108,  108,  108,  108,  108,  108,  112,  111,  107,
       73,   69,  112,   66,  112,  120,   59,  120,  120,  120,
      123,  123,  123,  123,  123,  123,  123,  157,  157,  157,
      157,  158,  158,  158,  158,  158,  227,    7,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,

      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227
    } ;

static const flex_int16_t yy_chk[722] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    4,    4,    3,    5,    4,
        6,   19,   19,   19,   20,   21,   21,   21,   24,   24,
       54,   54,   27,   28,  226,   27,   20,   21,   62,   62,

       79,  225,   28,   29,   30,  222,   27,   79,  221,   30,
       29,   34,  218,   20,  216,   28,   29,    3,   27,    4,
       28,   27,   30,   20,   21,   31,   79,   31,   28,   29,
       29,   30,   36,   34,   32,   30,   35,   29,   34,   20,
      215,   31,   29,   35,  214,   37,  210,   32,    5,   38,
        6,   31,   32,   31,   36,   39,  206,   35,   37,   36,
       32,   32,   38,   35,  205,   39,   40,   39,   41,   35,
       42,   37,   44,   32,  203,   38,   39,   40,   32,   42,
      202,   45,   39,   61,   61,  193,   71,   74,  190,   45,
       41,   39,   40,   39,   61,   41,   42,   43,   44,   44,

       45,   63,  188,   63,   43,   63,   63,   74,   45,   71,
       43,   72,   43,   71,   74,   45,   65,   65,   65,   43,
       75,   61,   72,   43,   43,   76,   77,   82,   65,  187,
       85,   43,   81,   75,   78,   76,   43,   72,   43,  183,
       78,   80,   81,   83,   85,   43,   75,   80,   78,   86,
       82,   76,   77,   77,   82,   65,   85,   84,   81,   83,
       78,   88,  182,   89,   91,   90,   78,   80,   84,   83,
       88,   95,   94,   91,   96,   86,   86,   89,   98,  181,
       99,  180,   97,   84,   95,  178,  101,   88,   90,   89,
       91,   94,   90,   97,  101,  103,   98,   95,  102,   94,

       96,   96,   99,  177,  104,   98,  103,   99,   97,  105,
      102,  122,  101,  113,  113,  114,  114,  116,  116,  118,
      118,  103,  104,  124,  102,  126,  114,  105,  115,  125,
      115,  104,  115,  115,  128,  127,  105,  122,  122,  129,
      131,  124,  132,  136,  128,  125,  127,  126,  134,  137,
      124,  129,  126,  114,  131,  125,  135,  138,  134,  142,
      128,  127,  135,  139,  132,  129,  131,  136,  171,  132,
      136,  143,  137,  144,  134,  143,  137,  167,  146,  138,
      144,  142,  135,  139,  138,  145,  142,  147,  148,  149,
      139,  151,  153,  153,  146,  143,  144,  163,  143,  152,

      144,  147,  143,  145,  146,  159,  144,  151,  152,  159,
      148,  149,  145,  147,  160,  148,  149,  151,  155,  155,
      156,  156,  161,  162,  164,  152,  165,  166,  160,  168,
      158,  159,  169,  164,  170,  172,  166,  173,  150,  175,
      160,  141,  165,  170,  161,  184,  173,  185,  140,  161,
      164,  168,  165,  166,  174,  172,  168,  176,  169,  169,
      170,  175,  172,  173,  179,  174,  175,  184,  176,  185,
      186,  186,  184,  189,  185,  191,  133,  194,  179,  192,
      174,  198,  197,  176,  196,  199,  195,  198,  194,  200,
      179,  130,  192,  123,  201,  121,  204,  191,  120,  189,

      189,  197,  191,  194,  195,  192,  196,  198,  199,  197,
      204,  196,  199,  195,  201,  200,  200,  207,  112,  208,
      209,  201,  204,  211,  110,  212,  219,  213,  220,  217,
      106,  209,  208,  212,  223,  224,  219,  100,   93,  220,
      207,  211,  213,  217,  207,  208,  209,   92,   87,   73,
      211,  212,  219,  213,  220,  217,  223,  224,   70,   64,
       59,  223,  224,  228,  228,  228,  228,  228,  228,  228,
      228,  228,  228,  228,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  229,  229,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  231,  231,  231,  231,  231,

      231,  231,  232,  232,  232,  232,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  234,   58,   52,
       33,   26,  234,   22,  234,  235,   12,  235,  235,  235,
      236,  236,  236,  236,  236,  236,  236,  237,  237,  237,
      237,  238,  238,  238,  238,  238,    7,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,

      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  227,  227,  227,  227,  227,  227,  227,  227,
      227
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[77] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 2 "scanner.l"

    #define  SHOW_TOKENS 0

    #include "syntax.tab.h"
    #include "hashtbl.h"
    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    #include <math.h>

    char string_buffer[256];
    int errorCounter = 0;

    void print_token(int token_id);
    int str_to_int(char *str);
    float hex_to_float(char *str);
    float str_to_float(char *str);
    int str_to_bool(char *str);
    char str_to_char(char *str);
    void yyerror(const char *err);

#line 732 "lex.yy.c"

#line 734 "lex.yy.c"

#define INITIAL 0
#define STRING 1
#define COMMENTS 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 37 "scanner.l"


#line 956 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 228 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 648 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 39 "scanner.l"
{ print_token( T_PROGRAM   );       return T_PROGRAM    ;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 40 "scanner.l"
{ print_token( T_CONST     );       return T_CONST      ;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 41 "scanner.l"
{ print_token( T_TYPE      );       return T_TYPE       ;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 42 "scanner.l"
{ print_token( T_COUPLE    );       return T_COUPLE     ;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 43 "scanner.l"
{ print_token( T_ARRAY     );       return T_ARRAY      ;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 44 "scanner.l"
{ print_token( T_OF        );       return T_OF         ;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 45 "scanner.l"
{ print_token( T_VAR       );       return T_VAR        ;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 46 "scanner.l"
{ print_token( T_FORWARD   );       return T_FORWARD    ;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 47 "scanner.l"
{ print_token( T_FUNCTION  );       return T_FUNCTION   ;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 48 "scanner.l"
{ print_token( T_PROCEDURE );       return T_PROCEDURE  ;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 49 "scanner.l"
{ print_token( T_INTEGER   );       return T_INTEGER    ;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 50 "scanner.l"
{ print_token( T_REAL      );       return T_REAL       ;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 51 "scanner.l"
{ print_token( T_BOOLEAN   );       return T_BOOLEAN    ;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 52 "scanner.l"
{ print_token( T_CHAR      );       return T_CHAR       ;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 53 "scanner.l"
{ print_token( T_STRING    );       return T_STRING     ;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 54 "scanner.l"
{ print_token( T_BEGIN     );       return T_BEGIN      ;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 55 "scanner.l"
{ print_token( T_END       );       return T_END        ;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 56 "scanner.l"
{ print_token( T_IF        );       return T_IF         ;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 57 "scanner.l"
{ print_token( T_THEN      );       return T_THEN       ;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 58 "scanner.l"
{ print_token( T_ELSE      );       return T_ELSE       ;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 59 "scanner.l"
{ print_token( T_CASE      );       return T_CASE       ;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 60 "scanner.l"
{ print_token( T_OTHERWISE );       return T_OTHERWISE  ;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 61 "scanner.l"
{ print_token( T_WHILE     );       return T_WHILE      ;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 62 "scanner.l"
{ print_token( T_DO        );       return T_DO         ;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 63 "scanner.l"
{ print_token( T_FOR       );       return T_FOR        ;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 64 "scanner.l"
{ print_token( T_DOWNTO    );       return T_DOWNTO     ;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 65 "scanner.l"
{ print_token( T_TO        );       return T_TO         ;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 66 "scanner.l"
{ print_token( T_READ      );       return T_READ       ;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 67 "scanner.l"
{ print_token( T_WRITE     );       return T_WRITE      ;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 68 "scanner.l"
{ print_token( T_LENGTH    );       return T_LENGTH     ;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 71 "scanner.l"
{ print_token( T_RELOP  );      return T_RELOP  ;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 72 "scanner.l"
{ print_token( T_RELOP  );      return T_RELOP  ;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 73 "scanner.l"
{ print_token( T_RELOP  );      return T_RELOP  ;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 74 "scanner.l"
{ print_token( T_RELOP  );      return T_RELOP  ;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 75 "scanner.l"
{ print_token( T_RELOP  );      return T_RELOP  ;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 76 "scanner.l"
{ print_token( T_ADDOP  );      return T_ADDOP  ;} 
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 77 "scanner.l"
{ print_token( T_ADDOP  );      return T_ADDOP  ;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 78 "scanner.l"
{ print_token( T_OROP   );      return T_OROP   ;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 79 "scanner.l"
{ print_token( T_MULDIVANDOP ); return T_MULDIVANDOP ;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 80 "scanner.l"
{ print_token( T_MULDIVANDOP ); return T_MULDIVANDOP ;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 81 "scanner.l"
{ print_token( T_MULDIVANDOP ); return T_MULDIVANDOP ;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 82 "scanner.l"
{ print_token( T_MULDIVANDOP ); return T_MULDIVANDOP ;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 83 "scanner.l"
{ print_token( T_NOTOP  );      return T_NOTOP  ;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 84 "scanner.l"
{ print_token( T_PAIROP );      return T_PAIROP ;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 85 "scanner.l"
{ print_token( T_PAIROP );      return T_PAIROP ;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 88 "scanner.l"
{ print_token( T_LPAREN );  return T_LPAREN     ;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 89 "scanner.l"
{ print_token( T_RPAREN );  return T_RPAREN     ;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 90 "scanner.l"
{ print_token( T_SEMI   );  return T_SEMI       ;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 91 "scanner.l"
{ print_token( T_DOTDOT );  return T_DOTDOT     ;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 92 "scanner.l"
{ print_token( T_DOT    );  return T_DOT        ;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 93 "scanner.l"
{ print_token( T_COMMA  );  return T_COMMA      ;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 94 "scanner.l"
{ print_token( T_ASSIGN );  return T_ASSIGN     ;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 95 "scanner.l"
{ print_token( T_EQU    );  return T_EQU        ;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 96 "scanner.l"
{ print_token( T_COLON  );  return T_COLON      ;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 97 "scanner.l"
{ print_token( T_LBRACK );  return T_LBRACK     ;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 98 "scanner.l"
{ print_token( T_RBRACK );  return T_RBRACK     ;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 100 "scanner.l"
{ print_token( T_BCONST );  yylval.boolval   = str_to_bool(yytext);   return T_BCONST  ;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 101 "scanner.l"
{ print_token( T_BCONST );  yylval.boolval   = str_to_bool(yytext);   return T_BCONST  ;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 102 "scanner.l"
{ print_token( T_ID     );  yylval.stringval = strdup(yytext);        return T_ID      ;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 103 "scanner.l"
{ print_token( T_ICONST );  yylval.intval    = str_to_int(yytext);    return T_ICONST  ;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 104 "scanner.l"
{ print_token( T_RCONST );  yylval.doubleval = str_to_float(yytext);  return T_RCONST  ;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 105 "scanner.l"
{ print_token( T_CCONST );  yylval.charval   = str_to_char(yytext);   return T_CCONST  ;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 108 "scanner.l"
{ strcpy(string_buffer,"");    BEGIN(STRING)   ;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 109 "scanner.l"
{ BEGIN(INITIAL);              (SHOW_TOKENS == 0? : printf("LINE[%d] STRING TOKEN: %s\n",yylineno,string_buffer) ); yylval.stringval = strdup(string_buffer); return T_SCONST  ;}
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 110 "scanner.l"
{ }
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 111 "scanner.l"
{   
                                if(strlen(yytext) == 2){
                                    if(strcmp(yytext,"\\n") == 0){
                                        strcat(string_buffer,"\n");
                                    }else if(strcmp(yytext,"\\t") == 0){
                                        strcat(string_buffer,"\t");
                                    }else if(strcmp(yytext,"\\b") == 0){
                                        strcat(string_buffer,"\b");
                                    }else if(strcmp(yytext,"\\v") == 0){
                                        strcat(string_buffer,"\v");
                                    }else if(strcmp(yytext,"\\f") == 0){
                                        strcat(string_buffer,"\f");
                                    }else if(strcmp(yytext,"\\r") == 0){
                                        strcat(string_buffer,"\r");
                                    }
                                }else{
                                    strcat(string_buffer,yytext);
                                }                                
                            }
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 130 "scanner.l"
{ yyerror("New line found wihtout \\.")        ;}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 131 "scanner.l"
{ yyerror("End of string without closing it.") ;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 132 "scanner.l"
{ yyerror("\nUNKNOWN CHARACTER.")              ;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 135 "scanner.l"
{ ( SHOW_TOKENS == 0? : printf("LINE[%d] Comment Found\n",yylineno) );  BEGIN(COMMENTS) ;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 136 "scanner.l"
{ BEGIN(INITIAL);  ( SHOW_TOKENS == 0? : printf("LINE[%d] Comment Ended \n",yylineno) );}
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 137 "scanner.l"
{ }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 138 "scanner.l"
{ }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 141 "scanner.l"
{ }
	YY_BREAK
case 74:
/* rule 74 can match eol */
YY_RULE_SETUP
#line 142 "scanner.l"
{ }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENTS):
#line 143 "scanner.l"
{ print_token( T_EOF );  return T_EOF  ;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 144 "scanner.l"
{ yyerror("UNKNOWN CHARACTER.")        ;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 146 "scanner.l"
ECHO;
	YY_BREAK
#line 1435 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 228 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 228 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 227);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 146 "scanner.l"


void print_token(int token_id){

    if(SHOW_TOKENS == 0){
        return;
    }

    if(token_id == T_ICONST){

        printf("LINE[%d] INTEGER TOKEN \'%s\'.Base 10: %d token id:%d\n",yylineno,yytext,str_to_int(yytext),token_id);

    }else if(token_id == T_RCONST){ 

        printf("LINE[%d] FLOAT TOKEN \'%s\'.Base 10: %f token id:%d\n",yylineno,yytext,str_to_float(yytext),token_id);

    }else{
        printf("LINE[%d] TOKEN \'%s\' (%d)\n",yylineno,yytext,token_id);
    }
}

int str_to_int(char *str){

    if((strncmp(str,"0x",2) == 0) || strncmp(str,"0X",2) == 0){
        return (int) strtoll(&str[2],NULL,16);
    }else{
        return (int) strtoll(str,NULL,10);
    }

}

int str_to_bool(char *str){

    if(str[0] == 'T'){
        return 1;
    }else if(str[0] == 'F'){
        return 0;
    }else{
        return 0;
    }

}

float str_to_float(char *str){

    if((strncmp(str,"0x",2) == 0) || strncmp(str,"0X",2) == 0){
        return hex_to_float(str);
    }else{
        return (float) strtof(str, NULL);
    }

}

float hex_to_float(char *str){

    //na balw na anagnwrizei meta apo . dekaexadiko px-> .FF123

    float num = 0.0;
    int i,length_real;
    char *character;

    //briskeis to string apo th teleia kai meta (dekadiko meros)
    character = strchr(str,'.');
    length_real = strlen(character)-1;

    //kaneis ton dekaexadiko prin thn teleia dekadiko
    num = (int)strtoll(&character[2],&character,16);

    //metatrepeis kai prostheteis kathe fora to epomeno dekaexadiko
    for(i=1;i<=length_real;i++){
        if(character[i] <= '9'){
            //afaireis ton arithmo sto ascii apo to 0 gia na pareis ton arithmo kai ton pollaplasiazeis gia na parei thn antistixh thesh sto dekadiko kommati
            num += (character[i] - '0') * (1/pow(16,i));
        }else{
            num += (character[i] + 10 - 'A') * (1/pow(16,i));
        }
    }

    return num;
}

char str_to_char(char *str){

    if(strlen(str) == 4){
        //to char einai tupou 'c' ara to string exei megethos 4 gia ta special kai na kanw ypostring me length 2 gia to matching
        char substr[2];
        substr[0] = str[1];
        substr[1] = str[2];
        if(strcmp(substr,"\\n") == 0){
            return '\n';
        }else if(strcmp(substr,"\\t") == 0){
           return '\t';
        }else if(strcmp(substr,"\\b") == 0){
            return '\b';
        }else if(strcmp(substr,"\\v") == 0){
            return '\v';
        }else if(strcmp(substr,"\\f") == 0){
            return '\f';
        }else if(strcmp(substr,"\\r") == 0){
            return '\r';
        }
    }else{
        return (char) str[1];
    }
}

void yyerror(const char *err){
    errorCounter += 1;
    printf("[ERROR - LINE %d] %s\n",yylineno,err);

    if(errorCounter == 5){
        printf("MAXIMUM NUMBER OF ERRORS DETECTED\n");
        exit(EXIT_FAILURE);
    }

    //prospatheia sbhsimo lanthasmenou xaraktira
    yyless(1);
}
