#define T_EOF         0
#define T_PROGRAM     1
#define T_CONST       2
#define T_TYPE        3
#define T_COUPLE      4
#define T_ARRAY       5
#define T_OF          6
#define T_VAR         7
#define T_FORWARD     8
#define T_FUNCTION    9
#define T_PROCEDURE   10
#define T_INTEGER     11
#define T_REAL        12
#define T_BOOLEAN     13
#define T_CHAR        14
#define T_STRING      15
#define T_BEGIN       16
#define T_END         17
#define T_IF          18
#define T_THEN        19
#define T_ELSE        20
#define T_CASE        21
#define T_OTHERWISE   22
#define T_WHILE       23
#define T_DO          24
#define T_FOR         25
#define T_DOWNTO      26
#define T_TO          27
#define T_READ        28
#define T_WRITE       29
#define T_LENGTH      30

#define T_RELOP       31
#define T_ADDOP       32
#define T_OROP        33
#define T_MULDIVANDOP 34
#define T_NOTOP       35
#define T_PAIROP      36
#define T_LPAREN      37
#define T_RPAREN      38
#define T_SEMI        39
#define T_DOTDOT      40
#define T_DOT         41
#define T_COMMA       42
#define T_ASSIGN      43
#define T_EQU         44
#define T_COLON       45
#define T_LBRACK      46
#define T_RBRACK      47

#define T_ID          48
#define T_ICONST      49
#define T_BCONST      50
#define T_CCONST      51
#define T_SCONST      52
#define T_RCONST      53
